server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # Приклад для майбутнього event-service
        # - id: event-service
        #   uri: lb://event-service
        #   predicates:
        #     - Path=/api/events/**
        #   filters:
        #     - StripPrefix=0

        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,routes
