spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/events
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  jwt:
    secret: ${JWT_SECRET:XZCWPq6HWsbE4Rcp5VdaXUL64wDrPYu07T2azl4URwo=}
    issuer: "event-booking"
    access-token-ttl-min: 60

