server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/events
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  open-in-view: false
